version: '3'

services:

  postgres_db:
    image: postgres:12.2
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user007
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #sudo chown 1001 ./redis/data/ ---> RUN this before launching
  redis_cache:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=whatsmyname
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6380:6379"
    volumes:
      - './redis/data:/bitnami/redis/data'